### ISSUE TITLE
OBS Websocket Interferes with Memebox?

### ISSUE THREAD

**Issue by jonathanbucci** [negue/meme-box#245]
When I launch Memebox without OBS running, it lets me configure everything just fine. I can even test my screens. Once I launch OBS I get a notice that OBSwebsocket has a new connection. Then Memebox dumps all of it's data and takes me to the getting started screen. It won't let me set up those three steps. If I close OBS, it reloads what I was doing previously. Is this because my websocket isn't using default settings? Why is it even trying to connect to my websocket?

**Comment by jonathanbucci** [comment]
I notice that the streamdeck advanced settings are using websocket port 4444 on the local host. Can I change the WS port of Memebox to fix this?

**Comment by negue** [comment]
Oh, yes OBS WebSocket uses the same Port - I'm sorry - I started this project before I found out OBS-Websocket uses the same  (might need to change it in the future, sorry again)

But once I found out that added the command line config for that:

https://github.com/negue/meme-box/blob/develop/tutorials/installation.md#commandline-options 

you can add this `--port=NEW_PORT` currently only with command line - I might need to add a config so that it can be used without a command line.

Could you try that ?

**Comment by jonathanbucci** [comment]
I just changed my OBS port from the default to another one. That way I don't have to worry about it going forward. It would be great if you used a different port in the future. It would also be great if you added some more notes about this to the Installation or getting started instructions. Cool product. Cheers!

**Comment by negue** [comment]
> I just changed my OBS port from the default to another one. 

Oh im sorry! :(

>  It would be great if you used a different port in the future. 

Lessons learned - yeah that will be a new port and a setting inside memebox ui (not only commandline)  so that should fix it for new users. I will ping you here once it can be changed.

> It would also be great if you added some more notes about this to the Installation or getting started instructions.

if you suggestions what the docs / or keywords on the docs should have please let me know - this is currently the hardest part of this project 😁  - creating the stuff is the easiest part haha  but docs thats a different level 😁

**Comment by jonathanbucci** [comment]
I work in systems integration and support. So while I can't code my way out of a paper bag, I am pretty good at documentation. How does this look?

On the Installation Guide under Running Meme-Box the following header and lines:
```
**Meme-Box & OBS WebSocket Server Port**
Meme-Box currently uses Port 4444 as the default port. OBS WebSocket also uses this as the default port. If you have the OBS WebSocket Server enabled you will need to change either the Meme-Box or OBS WebSocket port so that they don't conflict. 

If both are running on the same port at the same time, Meme-Box may lose its settings when OBS is running and OBS will show an alert that there is a new WebSocket connection.

To change Meme-Box's default port, add the following to the end of the command line command to start Meme-Box. In the future, I will add the ability to do this in the Meme-Box settings. If you use the Meme-Box Streamdeck plugin, remember to change the port number there to match for each Meme-Box button.

To change the OBSwebsocket port, open OBS Studio, click on Tools, and select WebSocket Server Settings. Change the server port to any other port. Press Okay. After doing this, check on other apps and plugins that rely on the WebSocket to work. You will have to enter the new port and usually renter the WebSocket password. Don't forget to check all of your Streamdeck (or similar) custom plugins after making this change.
```
Updated to mention the Meme-Box app.

**Comment by negue** [comment]
> So while I can't code my way out of a paper bag, I am pretty good at documentation. 

Very often documentation is key, which I'm lacking off^^ 

> How does this look?

Very well written!! I probably would 3-4 iterations until I'd get to this point^^

Thank you, I'll add that tomorrow to the docs.

For that, I'd like to add you to the contributors list - if you accept :)

**Comment by jonathanbucci** [comment]
You made a cool thing and give it away, the least I can do is help out a little bit in return. 

I'd be happy to be on the contributors list. Cheers! Ping me as you add features and I'd be happy to help in the future. I'm going to use this on my stream and get more acquainted with how it all works.

**Comment by negue** [comment]
@jonathanbucci sorry it took bit longer :D 

I've used your Docs on the release branch and added a note on current branch so that people always get the "released" one for the information  -> https://github.com/negue/meme-box#getting-started  what do you think about this way of "this here is the one of the branch but the one I linked is the released one" ?


@all-contributors add @jonathanbucci for doc

**Comment by jonathanbucci** [comment]
> @jonathanbucci sorry it took bit longer :D
> 
> I've used your Docs on the release branch and added a note on current branch so that people always get the "released" one for the information -> https://github.com/negue/meme-box#getting-started what do you think about this way of "this here is the one of the branch but the one I linked is the released one" ?
> 
> @all-contributors add @jonathanbucci for doc

Cool! The updated installation instructions look good.

The note was a bit confusing. Maybe try:
"Note: These are the current Getting Started / Tutorials for this branch. 
            To see the updated Getting Started / Tutorials from the released version - click here!"

**Comment by negue** [comment]
Thank you - yeah this is much better :)
