### ISSUE TITLE
Issue in: Action Edit Dialog - Recipe

### ISSUE THREAD

**Issue by matthewbrandt** [negue/meme-box#473]
Whenever the !pokemon command is triggered in Twitch chat, the media plays but then Memebox doesn't play any media afterwards (no matter if triggered by Twitch chat or directly via Triggers)

The Pokemon is configured as a recipe to trigger one of 9 random media sources. It was created prior to v2022.1-beta-1 (which I am currently running).

Logs are attached.
[memebox_tsed.2022-07-22.log](https://github.com/negue/meme-box/files/9172388/memebox_tsed.2022-07-22.log)

**Comment by negue** [comment]
Hey,

could it be that you are using queue's which then maybe lock up one of random triggers? (usually these would resolve them selves but I don't know yet)

I see that I need to improve the logs a bit - because there a good amount of preview images not showing in the overview and thats why creaing some spam in the logs (that I'll try to fix / extend these logs)

since some versions new videos will get the first a preview image - but all previous ones need to set that manually - please press 
![image](https://user-images.githubusercontent.com/842273/181917325-15162226-3940-4ced-b0ed-9cffd9f1f1ad.png)
that so that the previews will in the overview

**Comment by matthewbrandt** [comment]
I recreated a new Recipe with random videos (same video actions) and it still has the same issue. I do think it is queue related as the actions are all in the "meme" queue. Updating the screenshot position doesn't change anything either.

**Comment by negue** [comment]
Does the Recipe has a queue or even the same queue as the actions you added inside?

Could you try it without queues as well ?

**Comment by matthewbrandt** [comment]
I tested various things:
- Removing the queue on the actions solves the problem for the Recipe, but still doesn't play other actions
- Removing the queue on the actions and placing the queue on the Recipe works for the Recipe itself, but doesn't play other actions

So for now I removed the queue entirely from the Recipe and all the actions (that took a long time to edit each one).
I think the queue system needs to be looked at again with how it interacts with Recipes that use random logic.

**Comment by matthewbrandt** [comment]
Here are the configs for last night when the queue was still active and the config now with all the queues removed.
(Tokens have been removed from the config)
They're zipped as Github doesn't support JSON or BACKUP files.
[configs.zip](https://github.com/negue/meme-box/files/9275030/configs.zip)

**Comment by negue** [comment]
The new Pre-Release 2022.1-rc1 will have that fixed - it was an issue not of the queue but rather checking if one of the Actions are "done"
